commercialhaskell/stackage-server

Data/GhcLinks.hs, Handler/Download.hs, Handler/UploadStackage.hs, Handler/UploadV2.hs, Model.hs, Types.hs, config/models
Made this as a PR because I wanted a code review before merging into master.
I added an optional field to Stackage called GhcMajorVersion, which expresses the intent that the given snapshot should be used with the given major version of ghc.
=> Add ghc-major-version to Stackage table #88

templates/stackage-diff.hamlet
Missed that when moved from `Data.Map` to `Data.HashMap`.
=> Sort packages in snapshot diff

Handler/StackageHome.hs, Stackage/Database.hs, Stackage/Database/Types.hs, templates/stackage-home.hamlet
That's much better than what I did before. Didn't really now about `ltsBefore`/`nightlyBefore`
=> Query database to get the preceding SnapName

Handler/Feed.hs, Handler/OldLinks.hs, Handler/Sitemap.hs, Handler/Snapshots.hs, Handler/StackageHome.hs, Stackage/Database.hs, Types.hs, config/routes
I noticed that in some places we want to accept the input of sum-type:
```haskell
-- | There might be a better name for that type, suggestions are very welcome
data StackageBranch
= NightlyBranch      -- e.g /feed/nightly
| LtsBranch          -- e.g /feed/lts
| LtsMajorBranch Int -- e.g /feed/lts-3
-- /feed/#StackageBranch BranchFeedR GET
getBranchFeedR :: StackageBranch -> Handler
```
instead of that we have:
```haskell
data LtsMajor = LtsMajor Int
-- !/feed/#LtsMajor LtsMajorFeed GET
-- /feed/nightly LtsNightlyFeedR GET
-- /feed/lts LtsFeedR GET
getLtsMajorFeedR :: LtsMajor -> Handler
getNightlyFeedR :: Handler
getLtsFeedR :: Handler
```
This mostly applies to some handlers and functions in `Stackage.Database`.
So, I removed `LtsMajor` and added `StackageBranch`, and most other changes …
=> StackageBranch

Handler/Feed.hs, Handler/StackageHome.hs, Stackage/Database.hs, Stackage/Database/Types.hs, Stackage/Snapshot/Diff.hs, Types.hs, stackage-server.cabal, templates/stackage-diff.hamlet
```json
+zudov@x200 ~/prog/haskell/stackage-server $ http --json http://localhost:3000/diff/nightly-2015-10-08/nightly-2015-10-09
HTTP/1.1 200 OK
{
"comparing": [
"nightly-2015-10-08", 
"nightly-2015-10-09"
], 
"diff": {
"cabal-rpm": {
"nightly-2015-10-08": "0.9.7", 
"nightly-2015-10-09": "0.9.8"
}, 
"moesocks": {
"nightly-2015-10-08": "1.0.0.30", 
"nightly-2015-10-09": "1.0.0.40"
}, 
"opaleye": {
"nightly-2015-10-08": "0.4.1.0", 
"nightly-2015-10-09": "0.4.2.0"
}, 
"patches-vector": {
"nightly-2015-10-08": "0.1.1.0", 
"nightly-2015-10-09": "0.1.2.0"
}, 
"persistent-mysql": {
"nightly-2015-10-08": "2.3.0.1", 
"nightly-2015-10-09": "2.3.0.2"
}, 
"stateWriter": {
"nightly-2015-10-08": "0.2.4", 
"nightly-2015-10-09": "0.2.6"
}
}
}
```
=> Provide JSON representation of the snapshot diff

Handler/Package.hs
Since [github proxies external resources](https://github.com/blog/743-sidejack-prevention-phase-3-ssl-proxied-assets) we need to indicate that our badges are supposed to be changing.
From a brief study of https://github.com/atmos/camo it seems that unless we set something sensible in 'Cache-Control', the browser would be told to cache an image for a pretty long time.
https://github.com/atmos/camo/blob/da97a43fc385c24abded595b3f278802eb23586b/server.coffee#L103
Related: https://github.com/github/markup/issues/224
=> Set Cache-Control header on badges

.gitmodules, etc/build-deploy.sh, etc/docker/build.sh, etc/docker/push.sh, etc/kubernetes/deploy_rc.sh, etc/kubernetes/stackage-server-prod-rc.yaml, etc/kubernetes/stackage-server-prod-svc.yaml, stack.yaml
I haven't set up the CI system yet (don't want to use Travis because building Docker images means no caching for public projects, and there doesn't seem to be a way to get a public project to use our Pro account which would support caching for this case), but the new scripts are still useful.  Basically:
* `etc/build-deploy.sh prod`: build the code, push a Docker image, and rolling-update the production clusters
That uses these scripts, which you can also run on their own:
* `etc/docker/build.sh`: build a Docker image (gives it the `latest` tag)
* `etc/docker/push.sh prod [--tag TAG]`: push the local `latest` image to the Docker registry with `prod` and `prod_COMMITID` tags
* `etc/kubernetes/deploy_rc.sh prod`: rolling-update the production clusters to the image with tag `prod_COMMITID`
=> Script support for multi-AZ Kubernetes clusters and deployment from CI

Handler/Package.hs, Stackage/Database.hs, templates/package.hamlet, templates/package.lucius
- link to Hackage
- improve licensed by author markup
- print number of revdeps
- prettyName with ghc in parens
- list lts and nightly package versions on separate lines
=> improvements to package pages

templates/package.hamlet
This should improve the readability of the package's version list further:
compared to current master: https://github.com/fpco/stackage-server/pull/156#issuecomment-186184710.
=> package.hamlet: use a table and prettyNameShort to render version list

Import.hs, templates/package.hamlet, templates/stackage-diff.hamlet, templates/stackage-home.hamlet
Display links to changelogs of the packages on either side to aid in reviewing snapshot diffs. Since this uses a hash fragment to point to the id="changes" container, if there is no changelog the user will simply navigate to the package page.
=> Link to changelogs in snapshot diff

static/haddock/style.css
I believe the last commit to this file was aimed to that end, but there is a `:` missing, syntactically. I also thought it looks better if the font style matches that of `Source`.
Before:
After:
=> Haddock style: move selflink to the right

static/haddock/style.css
For computers that don't have either Ubuntu Mono or Monaco fonts installed, there should be a fallback font so we don't display code in a non-Monospaced font.
I've added Consolas for the Windows users (such as myself :smile:), and a final fallback to the default browser monospace font if even that fails.
This would fix #199.
=> Added code font styling fallback

templates/home.hamlet
This adds a link to the MAINTAINERS.md file, so that new maintains can find this information right from the stackage.org website.
=> Adds a link to the adding-a-package section.

.gitlab-ci.yml, etc/kube/deployment_template.yaml, etc/kube/service_template.yaml
Summary of changes:
* rename DOCKER_IMAGE to DEPLOYMENT_IMAGE
* docker image builds now run for any branch/tag
* include jobs for deploying and stopping the review app on kube
* review apps are deployed to the `fpco-untrusted` cluster
* review apps are available based the following URL scheme:
https://stackage-server-$CI_BUILD_REF_SLUG.review.fpco-untrusted.fpcomplete.com/
* master deploys to prod, and the previous staging env has been dropped
* import the kube specs we've used in CI/prod, update to use envvars
for APPROOT, DEPLOYMENT_APP, DEPLOYMENT_NAME, and DEPLOYMENT_IMAGE
Heads up: when merging this PR to master, gitlab will deploy that branch to prod.
=> update CI spec to use Gitlab review apps

templates/stackage-home.hamlet
Following up on discussion here: https://github.com/fpco/stackage/issues/2788#issuecomment-324012397
This builds for me, but I am sadly unable to test it locally. My attempts to do so hang on `Downloading database to stackage-database/database-download-1`.
=> Provide a link to offline snapshot doc archive

etc/load-testing/README.md, etc/load-testing/locustfile.py, etc/load-testing/requirements.txt
This PR adds load tests under `etc/load-testing` using [locust.io](https://www.locust.io).
Developers should be able to assess metrics from test instances using `locust --host='testinstance.somedomain'`.
If desired, a `README.md` with usage guidance can be prepared.
=> Load tests

Import.hs, stack.yaml
This provides the ability to aggregate results in Prometheus, allowing
metrics such as “average time per handler executed”. Summaries do not
provide this facility, and since their use-case for other views on
Prometheus is similar on `stackage-server`’s use-cases, it has been
completely changed to Histograms.
Since this demands a newer version of the Prometheus library, I have updated the snapshot and brought in bug-fixes from `all-cabal-metadata-tool` alongside in a separate commit.
=> Prometheus upgrade

.gitlab-ci.yml
Updates the CI and production images for the separate `stackage-server-hoogle-:env` deployments, so versions do not diverge upon new builds.
=> CI/CD for separate Hoogle queries deployment

src/Stackage/Snapshot/Diff.hs, templates/package-list.lucius, templates/stackage-diff.hamlet
Sometimes it's quite hard to spot the difference between package versions, as they look like a bunch of numbers to the user. This introduces highlighting them if version numbers have anything in common (determined with `commonPrefixes`) with color and adjusted text style. 
NB: That's a really crude implementation, because I couldn't manage to run neither development (`yesod devel`), nor non-development versions on my Linux box.
=> Highlight package version differences

static/haddock/style.css
This will hopefully fix: https://github.com/fpco/stackage-server/issues/222
Not tested locally, as there doesn't seem to be a easy way to run it locally as of now.
=> Enable synopsis back

README.md, package.yaml, src/Application.hs, src/Stackage/Database/Cron.hs
Right now, running stackage server requires AWS credentials and so.
This PR will help others to run this locally without needing any external infrastructure.
=> Support for local installation of stackage-server

.gitlab-ci.yml, etc/helm/.helmignore, etc/helm/Chart.yaml, etc/helm/templates/NOTES.txt, etc/helm/templates/_helpers.tpl, etc/helm/templates/cron_deployment.yaml, etc/helm/templates/deployment.yaml, etc/helm/templates/hoogle_deployment.yaml, etc/helm/templates/hoogle_service.yaml, etc/helm/templates/ingress.yaml, etc/helm/templates/service.yaml, etc/helm/values.yaml, etc/helm/values/production.yaml, etc/helm/values/staging.yaml
This PR instroduces two changes:
- Helm chart and the templates for 
- stakage-server services/deployment
- hoogle services/deployment
- cron services/deployment
- Update the ci deployment using helm instead of kubectl
- Update the runner images to have available helm binary
- Added `review_stop` job on gitlab-ci.yml to stop the jobs when it is needed
=> Setup Helm chart for deployment instead of kube config

templates/home.hamlet
In particular, highlight that Stackage is a community project,
explain how it relates to Hackage,
set expectations on how it's maintained and moves forward,
and add credits for development and maintenance sponsorship.
=> homepage: Add more details about Stackage.

src/Stackage/Database.hs, src/Stackage/Database/Haddock.hs, stack.yaml, templates/home.hamlet
Fixes #264. I slightly reworded the text by the link, as well.
Also includes minor changes that bump it up to lts-13.9
* `optSafe` is apparently now the default & therefore not exported
* `parseParas` now accepts a `Maybe Package`. I assume that passing in `Nothing` gets us to the behavior as before...
Works on my machine.
=> Haskell lang rename

app/stackage-server-cron.hs, src/Stackage/Database/Cron.hs, src/Stackage/Database/Query.hs
* `global-hints.yaml` is now used as a fallback for packages that are not included in the snapshot
* Fix ordering of dependencies on the package page
=> Fix priority of core packages:

src/Handler/Package.hs, src/Stackage/Database/Query.hs, src/Stackage/Database/Types.hs
At the top of the module some devs can add a pragma `{-# OPTIONS_HADDOCK hide, not-home #-}`
which makes haddock not be generated for these modules, despite that they are still exposed and can be imported from the outside.
Currently on stackage these modules have links generated for them, which result in 404s since there are no docs for those modules. This PR fixes that, by simply not generating links (but still showing the names) for such modules. Hackage seems to have the same behavior.
Good example is current `QuickCheck`:
* On hackage: https://hackage.haskell.org/package/QuickCheck
* On stackage: https://www.stackage.org/package/QuickCheck (note links), so this is a 404 https://www.stackage.org/haddock/nightly-2019-07-11/QuickCheck-2.13.2/Test-QuickCheck-Exception.html
* How it should …
=> Make sure links to haddocks are not generated for modules that have no haddock

src/Stackage/Database/Cron.hs, src/Stackage/Database/Query.hs
Currently [`doldol`](https://www.stackage.org/nightly-2019-07-29/package/doldol-0.4.1.2) is listed as deprecated, despite that it is not listed as such on Hackage. This has likely happened because the maintainer of doldol has deprecated the package temporarily and later undeprecated it. This PR implements automatic undeprecation of Hackage packages.
=> Implemented automatic undeprecation of previously deprecated packages

templates/stackage-diff.hamlet
Replaced "package-name-1.2.3.4 package-2.3.4.5" representation with
"package-name 1.2.3.4 → 2.3.4.5", since package name is always the same.
Also removed rogue `}` from the URL of the deleted package.
before: 
after: 
Not sure, though, what to do with these two wide mostly empty columns and how to improve discoverability of the fact the version number is a link to the doc exactly.
=> Improve the snapshot diff view

package.yaml, src/Data/WebsiteContent.hs, src/Handler/Blog.hs, src/Handler/Download.hs, src/Handler/Feed.hs, src/Handler/Haddock.hs, src/Handler/Hoogle.hs, src/Handler/MirrorStatus.hs, src/Handler/Package.hs, src/Handler/PackageDeps.hs, src/Handler/StackageHome.hs, src/Handler/StackageSdist.hs, src/Import.hs, src/Stackage/Database/Cron.hs, src/Stackage/Database/Github.hs, src/Stackage/Database/Haddock.hs, src/Stackage/Database/PackageInfo.hs, src/Stackage/Database/Query.hs, src/Stackage/Database/Schema.hs, src/Stackage/Database/Types.hs, src/Stackage/Snapshot/Diff.hs, src/Types.hs, stack.yaml
Use [commercialhaskell/core-cabal-files](https://github.com/commercialhaskell/core-cabal-files) repository as a fallback for core packages that are missing from Hackage. Here is a sample [`base-4.13.0.0`](https://lehins.net/nightly-2020-02-06/package/base-4.13.0.0) page
This also fixes "Depends on" count on each package page being one off, since now it will list `base` as well.
In order to get it fixed few things were required:
* Update to pantry-0.2.0.0 that supports Cabal-3.x which is great, cause now we can have cabal files with new syntax on stackage.org
* Update to nightly lts with ghc-8.8, since some dependencies were not happy about Cabal-3.x
* Ability to store fallback cabal files in pantry.
This PR depends on: commercialhaskell/pantry#15
=> External cabal files

src/Handler/Home.hs, src/Settings.hs, src/Stackage/Database/Cron.hs, src/Stackage/Database/Query.hs, src/Stackage/Database/Schema.hs, src/Stackage/Database/Types.hs, templates/home.hamlet
This PR mainly solves the problem of long delays before hoogle db can appear after a hoogle update, but it does even more than that:
* There is now a record of each generated hoogle version db for each snapshot, which means:
* even upon an upgrade we can easily downgrade hoogle version with no intervention
* we can now over time generate hoogle db for all snapshots.
* At each iteration of a cron job only 5 latest lts snapshots and 5 latest nightly snapshots that don't have current hoogle db generated, will get a new one generated for each of them. 
* If a snapshot previously had a hoogle db generated and it is available on S3, it will not be regenerated, but simply marked as available.
* Earlier two points mean that there is never duplicate generation of the same hoogle-version + snapshot …
=> Record available hoogle db files per snapshot + hoogle version

etc/helm/values/staging.yaml
During process with hoogle, the memory usage excceeds 2GiB and causes pod crashing loop.
=> Increase memory limitation for stackage-server-cron

src/Handler/Home.hs, templates/default-layout.hamlet, templates/home.hamlet, templates/snapshots-nav.hamlet
The main change here is to move recent snapshots from News into the Releases per ghc section.
(I haven't verified the rendering)
- Also move Snapshots left on the Navbar
- Remove \ before > on /snapshots
=> a few fixups

bench/main.hs, indices, src/Settings.hs, src/Stackage/Database/Schema.hs
Looks like it's impossible to reopen PR after a force push, so here is a new one instead of #302 
This one definitely improves things quite a bit. Trick is in the index on sorting on lts creation date.
I could never replicate it locally because it turns database/hdd cache was always kicking in on subsequent queries, so I would never notice stackage.org/package/packagename page to be that slow until today. That's why benchmarks of the query also run incredibly fast, because a query that is being benchmarked doesn't change.
=> Attempt to fix slow queries

README.md, src/Handler/Home.hs, stack.yaml, templates/home.hamlet
I bundled a few minor tweaks in here:
- lts-16.31
- mention `yesod devel` in Readme
- only show News if blog post is from last 6 years
(alternative solutions might include blogging more or putting News later if out of date,
but I think this change makes sense - untested with data though).
=> hide News if no recent blog posts

templates/stackage-home.hamlet
This is to simplify the top of snapshot pages.
I think by now for most people (myself at least) the resolver help text is mostly "invisible".
So feel it is better just to show the resolver with a link to the stack documentation on resolvers.
This seems more concise and compact: newcomers should read the docs to understand it properly anyway.
NB This builds but I haven't actually seen the result yet since `yesod devel` doesn't create any dummy snapshots,
but it should look something like this:
**[resolver](https://docs.haskellstack.org/en/stable/GUIDE/#resolvers-and-changing-your-compiler-version): lts-17.15**
=> replace snapshot pages' resolver help with direct link to the stack doc

templates/stackage-home.hamlet
One more small tweak to snapshot pages: drop the `<h3>Hoogle` section header.
I don't think it is really necessary
=> remove the <h3>Hoogle before the hoogle search box

src/Handler/StackageHome.hs
This patch adds the specification of what compiler to use for a snapshot using cabal's "with-compiler" option.
**Context**
cabal-install 3.8 has gained the ability of using remote imports in cabal project files (https://cabal.readthedocs.io/en/latest/cabal-project.html#conditionals-and-imports). This was done as a first attempt to support using stackage snapshots directly with cabal (see https://github.com/haskell/cabal/issues/7556 for a discussion of the problem).
In short, one can create a `cabal.project` file as follows
```
-- this is the default if no cabal.project file exists
packages: ./*.cabal
-- this is needed at the moment and is the subject of this PR
with-compiler: ghc-9.0.2
-- this is the new bit
import: https://www.stackage.org/lts-19.10/cabal.config
```
and cabal use the …
=> Add with-compiler to snapshot's cabal.config file

src/Settings.hs, src/Stackage/Database/Haddock.hs, src/Stackage/Database/Schema.hs
This isn't improving compatibility with amazonka-2.0 (which still hasn't been released to Hackage), or with esqueleto-3.5, but I thought it was a start.
Not sure whether CPP is the right approach since this application only really is deployed in a single instance, but I thought I'd share it.
=> Compatibility with newer dependencies

static/opensearchhoogle.xml, static/opensearchpackage.xml
Changed the protocol of the URL used as a custom search engine from `http` to `https`.
The reason for this change is that `www.stackage.org` only uses `https`, so every time the custom search engine is used,
a redirect from `http` to `https` occurs,
sacrificing the cleanliness of the history.
On `www.stackage.org`,
the HTTP header is set to
`strict-transport-security max-age=15724800; includeSubDomains` for HSTS,
so there's no need to try connecting via http.
This is a bit unclear to me as well,
but even though HSTS is set and a redirect is set for subsequent access, it seems that no communication is being made,
but it is left in the history.
In any case,
I think it's wasteful to constantly access http when it's specialized for https to the point of setting HSTS,
so I'm making this …
=> fix(opensearch): search url protocol: `http` -> `https`

src/Handler/Package.hs
With this change, the `/package/#PackageNameP/badge/#SnapshotBranch/` endpoint takes a new query string "color" that controls the badge color. The color can be specified as a hex code or a named color from [`Graphics.Badge.Barrier.Color`](https://www.stackage.org/haddock/lts/barrier/Graphics-Badge-Barrier-Color.html) in the `barrier` library. The badge color defaults to `brightgreen`, preserving default behavior when no query string is supplied.
Closes #329
=> Allow customizing badge color with query string

stack.yaml, templates/blog-post.hamlet, templates/package.hamlet
- fix dates in blog archive list to not be for current displayed post
- update url to stackage readme section on adding package
- bump to final lts-22.43
=> a fix and a url update

README.md, src/Application.hs, src/Handler/BuildPlan.hs, src/Handler/StackageHome.hs, static/haddock/style.css, templates/default-layout.hamlet, templates/home.hamlet, templates/hoogle.hamlet, templates/package.lucius, templates/spam-package.hamlet, templates/stackage-diff.hamlet, templates/stackage-home.hamlet
These 3 commits are unrelated but small and self-contained, so I thought easier to just combine in one PR:
- currently the date is shown for snapshots (which is mostly redundant for nightly snapshots), let's also include the time
- replace remaining references to `github.com/fpco/` with `github.com/commercialhaskell/`
- add a link on snapshot changes (diff) pages to the previous diff page, for easier navigation (main motivator for this PR)
Compiles fine but untested (since I don't have a local db setup)
=> add snapshot diff previous link and time to snapshot date

templates/stackage-diff.hamlet
This makes the names of the two [diffed](https://www.stackage.org/diff/lts-23.22/lts-23.23) snapshots links to their respective pages.
```
<snapshot1/>                         <snapshot2/>
s1diff1                              s2diff1
s1diff2                              s2diff2
:                                    :
```
=> diff: add links to snapshots

config/routes, package.nix, src/Handler/Snapshots.hs, src/Import.hs, templates/all-snapshots.hamlet
Continuing the idea from #353, I'm splitting HTML and JSON output into separate endpoints.
Changed: `/snapshots`: Only returns HTML instead of doing content negotiation
Added: `/api/v1/snapshots`: Only returns JSON
=> Split out SnapshotsR API
