commercialhaskell/stackage-server

- Handler/Alias.hs
- Handler/Hoogle.hs
- config/routes
- templates/stackage-home.hamlet
For #72. I have successfully tested this and downloaded a `.hoo` file.
(See also #85)
> Add download link for hoogle database

- Handler/StackageHome.hs
@snoyberg this is a bandaid fix for https://github.com/fpco/minghc/issues/58.
> Quick fix to allow old versions of stackage-sandbox to continue working

- Distribution/Package/ModuleForest.hs
- Handler/Package.hs
- stackage-server.cabal
- templates/package.hamlet
- templates/package.lucius
Closes #115
[screenshot](http://i.imgur.com/ygdXiGn.png)
> Lay out module listings hierarchically

- Application.hs
- Echo.hs
- Foundation.hs
- Handler/Package.hs
- Handler/Sitemap.hs
- Import.hs
- stackage-server.cabal
Tiny things
- removed reduntant CPP pragma
- fixed some warnings
> Small Cleanup

- Handler/StackageHome.hs
- Stackage/Database.hs
- Stackage/Database/Types.hs
- Stackage/Snapshot/Diff.hs
- config/routes
- stack.yaml
- stackage-server.cabal
- templates/stackage-diff.hamlet
- templates/stackage-home.hamlet
> Snapshot diff

- Handler/Package.hs
https://github.com/fpco/stackage-server/issues/138
This allows to pass `label`, and `style` parameter. `label` changes the text which precedes the resolver version, and `style` works in the same way as on shields.io.
> Allow change badge's label and style

- Handler/Package.hs
> Allow customizing entire badge label

- Handler/StackageHome.hs
- Stackage/Database.hs
- Stackage/Database/Types.hs
```json
$ http --json http://localhost:4000/lts-5.1
{
"snapshot": {
"ghc": "7.10.3",
"created": "2016-01-30",
"name": "lts-5.1"
},
"packages": [
{
"isCore": false,
"name": "abstract-deque",
"version": "0.3",
"synopsis": "Abstract, parameterized interface to mutable Deques."
},
{
"isCore": false,
"name": "abstract-par",
"version": "0.3.3",
"synopsis": "Type classes generalizing the functionality of the 'monad-par' library."
},
...
]
}
```
> Provide snapshot content as JSON

- Handler/Haddock.hs
- etc/scripts/stage_docker.sh
- static/haddock/style.css
Reverts fpco/stackage-server#196
> Revert "Merge master into prod"

- src/Handler/Feed.hs
A follow-up to #247 (couldn't test myself again due to to yesodweb/yesod#1471)
> Handler.Feed: colorize package version diff

- .gitlab-ci.yml
- etc/helm/templates/cron_deployment.yaml
- etc/helm/templates/deployment.yaml
- etc/helm/templates/hoogle_deployment.yaml
- etc/helm/values/production.yaml
- etc/helm/values/staging.yaml
Uncomment build stage and added a deployment command for the production environment
> review-apps: Update gitlab-ci.yml to deploy helm production chart

- src/Stackage/Database/Cron.hs
- src/Stackage/Database/Query.hs
* Fix memory leak during stackage cron job when caching is enabled (current cron job runs without caching, so it is not affected)
* Fix missing "Latest on Hackage" for packages from global-hints
> Two minor fixups

- src/Stackage/Database/Query.hs
Related to 07f3ef293fb557efcc7db1b5b552203d59ad8be7
> Fix the query for selecting the newest package version. 

- src/Stackage/Database/Cron.hs
- src/Stackage/Database/Query.hs
I'd like to get #268 and #269 fixes into production environment, since the #269 bug is a bit annoying
> Few minor fixes from yesterday

- src/Handler/Feed.hs
Problem
====
Too slow response from stackage.org/feed/.
So slow that my favorite RSS client (Slack's RSS integration) doesn't work due to timeout.
See https://github.com/fpco/stackage-server/issues/277 for details.
How?
====
Delete the content of the feed.
Why?
====
I can't confirm it's the true cause of the slowdown (because the server is too hard to run on my machine!).
But anyway I think the html content of the feed is too much:
I just want to know the new LTS Haskell is released by the feed.
I'll click the link if I do want to see the detailed updates.
In addition, there's a reason generating the content causes the slowdown:
Other pages using `getSnapshots` (e.g. https://www.stackage.org/snapshots, https://www.stackage.org/)
are not as slow as https://www.stackage.org/feed/.
So the …
> Try to fix #277 by deleting verbose info

- src/Foundation.hs
- src/Handler/Home.hs
- src/Stackage/Database/Cron.hs
- src/Stackage/Database/Query.hs
- src/Types.hs
- stack.yaml
- templates/default-layout-wrapper.hamlet
- templates/default-layout.hamlet
- templates/default-layout.lucius
- templates/home.hamlet
- templates/home.lucius
- templates/package.lucius
- templates/snapshots-nav.hamlet
- templates/stackage-home.hamlet
- templates/stackage-home.lucius
- rework the homepage layout and content
- enable navbar for homepage
- more navbar entries
- lts-16
- drop /?page
- hoogle-5.0.18
- improve /snapshots "buttons"
- improve snapshot top matter
- [q] better to use haskellstack.org for "get started"?
Opening this now for early review, comments, and feedback?
(I think it may need a little more hamlet/yesod foo, but I am reasonably happy so far.)
> homepage rework and other improvements

- templates/default-layout.lucius
- templates/home.hamlet
- templates/package.hamlet
- templates/package.lucius
- templates/stackage-home.hamlet
- templates/stackage-home.lucius
Okay one more PR :-)
Main changes:
- default to larger 16px everywhere
- reorder package pages a little, including display deps earlier
- simplify snapshot resolver text
(rendering of latter 2 is untested)
> package tweaks; 16px; simplify resolver

- bench/main.hs
- src/Handler/PackageList.hs
- src/Handler/StackageHome.hs
Fix benchmarks and disable two less useful pages that are ridiculously slow: #299 and #300
> Disable the really slow pages

- templates/stackage-home.hamlet
to address commercialhaskell/stackage#5794
> stackage-home snapshot: be clearer about --resolver

- README.md
- app/stackage-server-cron.hs
- package.yaml
- src/Stackage/Database/Cron.hs
- src/Stackage/Database/PackageInfo.hs
- src/Stackage/Database/Query.hs
- src/Stackage/Snapshot/Diff.hs
- src/Types.hs
- stack.yaml
closes #315 and rebases deps to lts-18
Actually untested (since I was lazy to setup pq) but credit goes to @alaendle for pointing out the suspect code.
> bump to lts-18 and fix ordering issue in snapshot diff

- LICENSE
- app/stackage-server-cron.hs
- config/settings.yml
- src/Application.hs
- src/Control/SingleRun.hs
- src/Data/WebsiteContent.hs
- src/Handler/DownloadStack.hs
- src/Handler/Haddock.hs
- src/Handler/MirrorStatus.hs
- src/Handler/StackageIndex.hs
- src/Settings.hs
- src/Stackage/Database/Cron.hs
- src/Stackage/Database/PackageInfo.hs
- src/Stackage/Database/Query.hs
- src/Stackage/Database/Schema.hs
- src/Stackage/Database/Types.hs
- src/Stackage/Snapshot/Diff.hs
- src/Types.hs
- stack.yaml
- static/opensearchhoogle.xml
- static/opensearchpackage.xml
- templates/default-layout.hamlet
- templates/home.hamlet
These were the changes I made during the handover process. Almost all of the changes are already live on stackage.org.
By volume, most of the changes are to do with updating dependencies. There was also some work done to support Cloudflare's R2.
Skip to the bottom to see my new attribution mentioning both FP Complete and Haskell Foundation.
> Handover patches

- docker/Dockerfile.base-build
- docker/Dockerfile.base-run
(being conservative here to avoid any surprises hopefully)
> update docker base images to pid1:20.04
